# Generated by Django 4.2.8 on 2024-02-16 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0005_journalcomment_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalcomment',
            name='staff',
        ),
    ]
