# Generated by Django 4.2.8 on 2024-02-17 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0006_remove_journalcomment_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journaltransactionhistory',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.journal'),
        ),
    ]
