# Generated by Django 4.2.8 on 2024-02-17 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0001_initial'),
        ('Company_Staff', '0007_alter_journaltransactionhistory_journal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journaltransactionhistory',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails'),
        ),
        migrations.AlterField(
            model_name='journaltransactionhistory',
            name='login_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.logindetails'),
        ),
    ]
