# Generated by Django 4.2.8 on 2024-02-19 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0001_initial'),
        ('Company_Staff', '0010_alter_journalcomment_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalrecievedidmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails'),
        ),
    ]
