# Generated by Django 4.2.8 on 2024-02-21 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0001_initial'),
        ('Company_Staff', '0012_journalrecievedidmodel_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='login_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.logindetails'),
        ),
    ]
