# Generated by Django 4.2.8 on 2024-02-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0014_chart_of_accounts_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
