# Generated by Django 4.2.8 on 2024-03-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0015_alter_journal_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='credits',
            field=models.DecimalField(decimal_places=10, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='debits',
            field=models.DecimalField(decimal_places=10, max_digits=10, null=True),
        ),
    ]
