# Generated by Django 4.2.8 on 2024-03-15 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0016_alter_journalentry_credits_alter_journalentry_debits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='credits',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='debits',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
