# Generated by Django 4.2.8 on 2024-03-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0017_alter_journalentry_credits_alter_journalentry_debits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='journal_attachments/'),
        ),
    ]
