# Generated by Django 4.2.8 on 2024-03-20 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0021_remove_journalrecievedidmodel_journal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='journal',
            new_name='jour',
        ),
    ]
