# Generated by Django 4.2.8 on 2024-03-26 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0022_rename_journal_journal_jour'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='subtotal_credit',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='subtotal_debit',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='journalrecievedidmodel',
            name='user',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='credit_difference',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='debit_difference',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='total_credit',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='total_debit',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
