# Generated by Django 4.2.8 on 2024-03-26 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0023_journal_subtotal_credit_journal_subtotal_debit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='subtotal_credit',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='subtotal_debit',
        ),
        migrations.AlterField(
            model_name='journal',
            name='credit_difference',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='debit_difference',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='total_credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='total_debit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
